spring.application.name=pastebin

server.port=${SERVER_PORT:8081}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/pastebin_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:asterisk}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
spring.data.redis.database=${SPRING_DATA_REDIS_DATABASE:0}

spring.thymeleaf.cache=false

springdoc.swagger-ui.path=/swagger-ui.html

app.jwt.secret=${APP_JWT_SECRET:PastebinSecretKeyForJwtTokenGenerationPastebinSecretKey123456}
app.jwt.expiration-ms=${APP_JWT_EXPIRATION_MS:86400000}

spring.devtools.restart.enabled=false